### ISSUE TITLE
[EPIC] Zoneless and signal based application 

### ISSUE THREAD

**Issue by nramc** [nramc/journeys#312]
**Overview / Introduction**
Since the Angular team is moving towards zoneless framework strategy, we need to prepare Journey application for that and to improve application and for better maintainability we need to use recommended signal api to replace zone based change detection to push change detection. 

**Acceptances Criteria**
AC 1: Identity places where signal can be used instead of decorators such as input, output and viewChild, viewContent
AC 2: Replace implementation with signal api
AC 3: Prefer standalone and signal based components to increase reusability 
AC 4: Use Push change detection policy
AC 5: Fix sonar issues as much as if possible
AC 6: Remove unused/empty scss files

**Additional Contexts **

- [x] MarkerPopupComponent - Easy
- [x] MediaGalleryComponent - Medium #371 
- [x] PageHeaderComponent - Easy
- [x] SideNavbarComponent - Medium - #372
- [x] TimelineComponent - High - https://github.com/nramc/journeys/issues/387
- [x] WorldMapComponent - High
- [x] DisableIfNoRoleExistsDirective - Medium - https://github.com/nramc/journeys/issues/388
- [x] HasRoleDirective - Medium - https://github.com/nramc/journeys/issues/408
- [x] GalleryComponent - Medium - https://github.com/nramc/journeys/issues/409
- [x] EditJourneyBasicDetailsComponent - High - https://github.com/nramc/journeys/issues/410
- [x] #411
- [x] #419
- [x] #420
- [x] #421
- [x] #422
- [x] #437
- [x] #480
- [x] #482
- [x] #481
- [x] #438
- [x] #439

Clean feedback components

- [x] #491
- [x] #494
- [x] #496
- [x] #499
- [x] Refactor EditJourneyImagesDetailsComponent to remove legacy implementation
- [x] Refactor EditJourneyPublishDetailsComponent to remove legacy implementation
- [x] Refactor EditJourneyVideosDetailsComponent to remove legacy implementation
- [x] #503
- [x] #504
