### ISSUE TITLE
[EPIC] Edit Geo Details ui/ux improvements 

### ISSUE THREAD

**Issue by nramc** [nramc/journeys#339]
- [x] All journey edit pages after successful update disable fields and display edit button to indicate data saved successfully
- [x] #522
- [x] Move Country, City & title to Geo Details object
- [x] Merge all geo information in one section, move location selection to geo section
- [x] Combine new journey creation with edit page, then remove new page completely to simplify flow and functionality 
- [x] Show raw GeoJson in model dialog on demand 
- [x] Remove category and use icon as category, since category flooding data everywhere
