### ISSUE TITLE
[EPIC] Reduce complexities for managing styles

### ISSUE THREAD

**Issue by nramc** [nramc/journeys#600]
**Overview / Introduction**
Due to varies styles used from various frameworks, libraries and utilities. it is really complex now to manage all styles with varies compatibility issues. I would suggest to remove all other outdated and not officially supported style frameworks and libraries.

**Acceptances Criteria**

- [x] #617
- [x] Remove bootstrap watch theme
- [x] Remove Bootstrap for angular
- [x] Remove bootstrap
- [x] #601
- [x] #619
- [x] define application theme in tailwind case
- [x] application rebranding 
- [x] [Feature] Convert logout component updated with mat card for better UI/UX #609
- [x] [Feature] Streamline success and error message highlighter #611
- [x] [Bug]: GeoCoding location population is not working when location searched #612
- [x] [Feature] Replace ngbDropdown with mat select #426
- [x] #613
- [x] #614
- [x] #615
- [x] Feasibility load map tiles in dark mode
- [x] Test as Guest user to verify access privilege 
- [x] #624
- [x] #631
- [ ] 

**Additional Contexts **
